<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-20
 * Time: 17:33
 */

class model_pinping_file extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_file'; // TODO: Change the autogenerated stub
    }
}