<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-11
 * Time: 18:18
 */

class model_pinping_fineproject extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_fine_project'; // TODO: Change the autogenerated stub
    }
}