<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:37
 */

class model_pinping_position extends hlw_components_basemodel
{
    public  function tableName()
    {
        return 'mx_position'; // TODO: Change the autogenerated stub
    }
}