<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 16:33
 */

class model_pinping_projectstatus extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_project_status'; // TODO: Change the autogenerated stub
    }
}