<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-18
 * Time: 17:09
 */

class model_pinping_ranktarget extends hlw_components_basemodel
{
    public function tableName() {
        return 'mx_rank_target'; // TODO: Change the autogenerated stub
    }

    /**
     * @desc  获取目标业绩
     * @return array
     */
    public function lists() {
        $list = $this->select();
        $list = $list->items ? $list->items : [];
        $data = [];
        foreach ($list as $info) {
            $key = $info['typeId'] . '_' . $info['rankId'];
            $data[$key] = $info['target'];
        }
        return $data;
    }
}