<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-18
 * Time: 17:09
 */

class model_pinping_ranktarget extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_rank_target'; // TODO: Change the autogenerated stub
    }
}