<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-07-17
 * Time: 17:27
 */

class model_pinping_resumework extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_resume_work'; // TODO: Change the autogenerated stub
    }
}