<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-07-17
 * Time: 17:29
 */

class model_resumeproject extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_resume_project'; // TODO: Change the autogenerated stub
    }
}