<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-07-17
 * Time: 17:22
 */

class model_pinping_resumeedu extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_resume_edu'; // TODO: Change the autogenerated stub
    }
}