<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:40
 */

class model_pinping_roleDepartment extends hlw_components_basemodel
{
    public function tableName() {
        return 'mx_role_department'; // TODO: Change the autogenerated stub
    }

    /**
     * @desc 获取下属部门部门ID
     * @param int $departmentId
     * @return string
     */
    function getSubDepartmentBrId($departmentId = 0) {
        if ($departmentId <= 0) {
            return 0;
        }
        static $list = [];
        array_push($list, $departmentId);
        $sons = $this->select(['parent_id' => $departmentId]);
        $sons = $sons->items ? $sons->items : [];
        foreach ($sons as $sonDep) {
            $id = $sonDep['department_id'];
            array_push($list, $id);
            if (!$sonInfo = $this->selectOne(['parent_id' => $id])) {
                continue;
            }
            if ($id <= 0) {
                continue;
            }
            $this->getSubDepartmentBrId($sonInfo['department_id']);
        }
        return implode(',', $list);
    }

    public function getAllDepart($parent) {
        $ones = $this->select(['parent_id' => $parent]);
        $sons = $ones->items ? $ones->items : [];
        $data = [];
        foreach ($sons as $info) {
            $id = $info['department_id'];
            $name = $info['name'];
            $data[$id] = ['id' => $id, 'name' => $name, 'p_id' => $info['parent_id']];
        }
        foreach ($data as &$one) {
            $patentId = $one['id'];
            $sons = $this->select(['parent_id' => $patentId]);
            $sons = $sons->items ? $sons->items : [];
            foreach ($sons as $info) {
                $id = $info['department_id'];
                $name = $info['name'];
                $one['sons'][] = ['id' => $id, 'name' => $name, 'p_id' => $info['parent_id']];
            }
        }
        return $data;
    }

    /**
     * @desc 部门数据
     * @return array
     */
    public function lists() {
        $list = $this->select();
        $list = $list->items ? $list->items : [];
        $data = [];
        foreach ($list as $info) {
            $data[$info['department_id']] = $info['name'];
        }
        return $data;
    }

    /**
     * @desc 上级列表
     * @return array
     */
    public function pList() {
        $all = $this->lists();
        $list = $this->select();
        $list = $list->items ? $list->items : [];
        $dataP = [];
        foreach ($list as $info) {
            $dataP[$info['department_id']] = ['name' => $all[$info['parent_id']], 'id' => $info['parent_id']];
        }
        return $dataP;
    }
}
