<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:33
 */

class model_pinping_role extends hlw_components_basemodel
{
    public function tableName() {
        return 'mx_role'; // TODO: Change the autogenerated stub
    }

    /**
     * @desc 根据职位获取role
     * @param $positionIds
     * @return array
     */
    public function getRolesByPosition($positionIds) {

        $roleList = $this->select("position_id in ({$positionIds})");
        $positions = isset($roleList->items) ? $roleList->items : [];
        $roles = '';
        foreach ($positions as $info) {
            $roles .= $info['role_id'] . ',';
        }
        return rtrim($roles, ',');
    }
}