<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:33
 */

class model_pinping_role extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_role'; // TODO: Change the autogenerated stub
    }
}