<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:40
 */

class model_pinping_roleDepartment extends hlw_components_basemodel
{
    public function tableName() {
        return 'mx_role_department'; // TODO: Change the autogenerated stub
    }

    /**
     * @desc 获取下属部门部门ID
     * @param int $departmentId
     * @return string
     */
    function getSubDepartmentBrId($departmentId = 0) {
        if ($departmentId <= 0) {
            return 0;
        }
        static $list = [];
        array_push($list, $departmentId);
        $sons = $this->select(['parent_id' => $departmentId]);
        $sons = $sons->items ? $sons->items : [];
        foreach ($sons as $sonDep) {
            $id = $sonDep['department_id'];
            array_push($list, $id);
            if (!$sonInfo = $this->selectOne(['parent_id' => $id])) {
                continue;
            }
            if ($id <= 0) {
                continue;
            }
            $this->getSubDepartmentBrId($sonInfo['department_id']);
        }
        return implode(',', $list);
    }
}