<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:40
 */

class model_pinping_roleDepartment extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'mx_role_department'; // TODO: Change the autogenerated stub
    }
}