<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:17
 */

class model_pinping_userAttendance extends hlw_components_basemodel
{
    public function tableName() {
        return 'mx_user_attendance'; // TODO: Change the autogenerated stub
    }

    /**
     * @desc 考勤数据添加
     * @param $data
     * @return mixed
     */
    public function addAll($data) {
        $res = $this->insertall($data);
        return $res;
    }

    /**
     * @desc 考勤列表
     * @param array $day
     * @return array
     */
    public function lists($day) {
        if (!$day) {
            $currentMoth = strtotime(date("Y-m-01 00:00:00", time()));
            $where['month'] = $currentMoth;
        } else {
            $where['month'] = strtotime(date("Y-m-01 00:00:00", strtotime($day)));
        }
        $list = $this->select($where, '*', '', ['id' => 'desc']);
        $list = isset($list->items) ? $list->items : [];
        $data = [];
        foreach ($list as $info) {
            $data[$info['role_id']] = ['attend_day' => $info['attendance_days'], 'work_days' => $info['work_days']];
        }
        return $data;
    }

    public function info($where) {
        $info = $this->selectOne($where);
        return $info;
    }

    public function updateInfo($condition = "", $item = "") {
       return $this->update($condition, $item);
    }

}