<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:17
 */

class model_pinping_user extends hlw_components_basemodel
{

    protected $rankModel;
    static $types = [
        1 => '面试快',
        2 => '入职快',
        3 => '专业猎头',
        4 => '猎萝卜',
        5 => 'BD'
    ];

    public function primarykey() {
        return 'user_id';
    }

    public function tableName() {
        return 'mx_user'; // TODO: Change the autogenerated stub
    }

    public function __construct($pkid = false) {
        parent::__construct($pkid);
        $this->rankModel = new model_pinping_jobRank();
    }

    /**
     * @desc 用户列表获取
     * @param $day
     * @param $name
     * @param $type
     * @param $department
     */
    public function userReachList($day, $name, $type, $department) {
        $roles = '';
        $where = "status = 1";

        //获取部门员工IDs
        $department > 0 && $roles = $this->departmentRoles($department);
        $roles && $where .= " and role_id in ({$roles})";
        $name && $where .= " and full_name like '%{$name}%' ";
        $type && $where .= " and type = {$type} ";
//        $ranks = $this->ranks();
//        $workDays = $this->workDays($day);
        $item = "user_id,role_id,status,type,job_rank,name,full_name,entry";
        $list = $this->select($where, $item, '', "order by user_id desc");
        return $list;
        die;

    }

    /**
     * @desc 获取用户数组
     * @param $where
     * @return array
     */
    public function users($where) {
        $users = $this->select($where, "user_id,full_name", '', ['user_id' => 'desc']);
        $list = $users->items;
        $return = [];
        foreach ($list as $info) {
            $return[$info['user_id']] = trim($info['full_name']);
        }
        return $return;
    }

    /**
     * @desc  获取部门下面的员工roles
     * @param $departmentId
     * @return string
     */
    private function departmentRoles($departmentId) {
        $departmentModel = new model_pinping_roleDepartment();
        $positionModel = new model_pinping_position();
        $roleModel = new model_pinping_role();
        $departments = $departmentModel->getSubDepartmentBrId($departmentId);
        $positionIds = $positionModel->positionIds($departments);
        $positionIds = implode(',', $positionIds);
        $roles = $roleModel->getRolesByPosition($positionIds);
        return $roles;
    }

    /**
     * @desc  职位级别
     * @return array
     */
    private function ranks() {
        return $this->rankModel->ranks();
    }

    /**
     * @desc 产品类型
     * @return array
     */
    private function types() {
        return self::$types;
    }

    /**
     * @desc 出勤数据
     * @return array
     */
    private function workDays() {
        $attendanceModel = new model_pinping_userAttendance();
        $list = $attendanceModel->lists();
        return [];
    }

    /**
     * @desc  原始晋级目标
     * @return array
     */
    private function target() {
        return [];
    }

    /**
     * @desc  实际业绩数据
     * @return array
     */
    private function achievements() {
        return [];
    }

    /**
     * @desc  计算折算业绩
     * @param $userId
     * @return int
     */
    private function discountAchieve($userId) {
        return 1;

    }

}