<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:17
 */

class model_pinping_user extends hlw_components_basemodel
{

    public function tableName()
    {
        return 'mx_user'; // TODO: Change the autogenerated stub
    }
}