<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-06-12
 * Time: 17:17
 */

class model_pinping_userAttendance extends hlw_components_basemodel
{
    public function tableName() {
        return 'mx_user_attendance'; // TODO: Change the autogenerated stub
    }

    /**
     * @desc 考勤数据添加
     * @param $data
     * @return mixed
     */
    public function addAll($data) {
        $res = $this->insertall($data);
        return $res;
    }

    /**
     * @desc 考勤列表
     * @param array $where
     * @return DbData
     */
    public function lists($where = []) {
        if (!$where) {
            $currentMoth = strtotime(date("Y-m-01", time()));
            $where['create_time'] = $currentMoth;
        }
        $list = $this->select($where, '*', '', ['id' => 'desc']);
        return $list;
    }
}