<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-07-12
 * Time: 16:59
 */

class model_huiliewang_company extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'phpyun_company'; // TODO: Change the autogenerated stub
    }
}