<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-07-16
 * Time: 19:56
 */

class model_huiliewang_resumeexpect extends hlw_components_basemodel
{
    public function tableName()
    {
        return 'phpyun_resume_expect'; // TODO: Change the autogenerated stub
    }
}